baseURL = "https://robinbb.com/"
languageCode = "en-us"
title = "robinbb"
Copyright = "Copyright 2023 by Robin Bate Boerop. All rights reserved."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 12
enableRobotsTXT = true

[Author]
  name = "Robin Bate Boerop"

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

# SectionPagesMenu = "main"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  # category = "categories"
  # series = "series"

[params]
  title = "robinbb"
  author = "Robin Bate Boerop"
  description = "Robin Bate Boerop's Blog"
  favicon = "/granola-favicon.ico"
  images = [ "/images/robinbb-profile-photo-bw.jpeg", "/images/robinbb-books-background-1.jpeg" ]
  body_classes = "bg-white black pt-sans-narrow"
  background_color_class = "bg-white"
  twitter = "https://twitter.com/robinbateboerop/"
  github = "https://github.com/robinbb/"
  gitlab = "https://gitlab.com/robinbb/"
  linkedin = "https://www.linkedin.com/in/robinbb/"
  # instagram = "https://www.instagram.com/robinbateboerop/"
  cover_dimming_class = "bg-black-60"
  # commentoEnable = false
  # toc = false
  # featured_image = "/images/robinbb-books-background-1.jpeg"
  # recent_posts_number = 2
  # # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # site_logo = ""
  # facebook = ""
  # youtube = ""
  # mastodon = ""
  # slack = ""
  # stackoverflow = ""
  # rss = ""
